- hosts: raulaxxo.cl  # reemplaza <nombre-del-servidor> por el nombre o dirección IP del servidor
  become: true

  tasks:
    - name: Set timezone
      timezone:
        name: America/Santiago
        
    - name: Print return information from the previous task
      ansible.builtin.debug:
      var: result
      verbosity: 2
