- hosts: raulaxxo.cl  # reemplaza <nombre-del-servidor> por el nombre o dirección IP del servidor
  become: true

  tasks:
    - name: set timezone
      timezone:
        name: America/Santiago
        
    - name: Print version
      debug:
        msg: " Time Zone : {{ timezone.stdout }}"
